multirtail:
    paths: ['/path/to/many/logs/*', '/path/to/one.log']
    debug: False
    showchanges: False
rtail:
    cmd: './node_modules/rtail/cli/rtail-client.js'
    args: '--parse-date false'
    host: 'localhost'